# Generated by Django 5.2.4 on 2025-07-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
